### ISSUE TITLE
你好，根据教程，还是没有成功启动G729的配置，求帮忙

### ISSUE THREAD

**Issue by WiiliamChik** [zero-li/AndroidPractice#1]
我用的是pjsip-2.8，我直接解压缩pjsip_souce里面的bcg729.zip，得到的bcg729目录应该是符合下面的结构的
<pre>bcg729
    |-- include
        |-- bcg729
            |-- decoder.h
            |-- encoder.h
    |-- lib
        |-- libbcg729.so</pre>

但我运行编译pjsip的命令是，如下
<pre>NDK_TOOLCHAIN_VERSION=4.9 TARGET_ABI=armeabi-v7a APP_PLATFORM=android-22 ./configure-android --use-ndk-cflags --with-ssl=/usr/local/ssl/ --with-bcg729=/Users/WilliamChik/Documents/develop/bcg729</pre>

得到了下面的错误信息
<pre>Using bcg729 prefix... /Users/WilliamChik/Documents/develop/bcg729
checking bcg729 usability... no</pre>

意思就是没开启g729，求问哪里出错了呢

**Comment by zero-li** [comment]
在编译G729的 脚本build_bcg729.sh中，采用的是armeabi ，
```
 -DCMAKE_ANDROID_ARCH_ABI=armeabi \
```
在您的编译pjsip中采用的是
```
TARGET_ABI=armeabi-v7a 
```
改为
```
NDK_TOOLCHAIN_VERSION=4.9 TARGET_ABI=armeabi APP_PLATFORM=android-17 ./configure-android --use-ndk-cflags --with-ssl=/usr/local/ssl/ --with-bcg729=/Users/WilliamChik/Documents/develop/bcg729
```

* 另，APP_PLATFORM 版本最好统一

**Comment by zero-li** [comment]
12
